# Generated by Django 4.2 on 2026-03-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_first_name_customer_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lease_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lease_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
