# Generated by Django 4.2 on 2026-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
