# Generated by Django 4.2 on 2026-04-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('dueDate', models.DateField()),
                ('billingMonth', models.CharField(max_length=50)),
                ('roomRental', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('elecBill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waterBill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isPaid', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billingMonth', models.CharField(max_length=50, unique=True)),
                ('pea_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pwa_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
