# Generated by Django 4.2 on 2026-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invoice_utilitycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
