# Generated by Django 4.2 on 2026-06-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_historylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='room_rental_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
